[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
diamond_hands = "Bbz4dnkiRz9oSjdg8H42KqWrhveDKTMRSB7b7HBADy3Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/yow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
